obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.365
footprint_padding: 0.0

inflation_radius: 1.55
transform_tolerance: 0.5

observation_sources: scan
scan:
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true



map_type: costmap
